### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by Julius-Plehn** [oliver-pola/OneMillionPostsCorpus#1]
- fastText: https://github.com/facebookresearch/fastText
- Subwords: https://github.com/rsennrich/subword-nmt
- Text Classification: https://blog.mimacom.com/text-classification/

- Word Embeddings: 
https://github.com/devmount/GermanWordEmbeddings
https://deepset.ai/german-word-embeddings

**Comment by oliver-pola** [comment]
Die Daten aus https://deepset.ai/german-word-embeddings habe ich mal probiert, weiß damit aber nichts anzufangen, kann sie nicht in ein word2vec model laden, ist nicht das Standardformat.

Die Daten aus https://github.com/devmount/GermanWordEmbeddings lassen sich laden, siehe 1017c97 und 0d279e3 . Allerdings weiß ich dort nicht, wie mit Worten umzugehen ist, die nicht im Vokabular sind, z.B. solche Exoten wie "ist" und "ein".

**Comment by oliver-pola** [comment]
Man müsste natürlich das Preprocessing genauso machen, wie die pretrained Embeddings entstanden sind. Für die benutzbaren Daten aus https://github.com/devmount/GermanWordEmbeddings siehe https://github.com/devmount/GermanWordEmbeddings/blob/master/preprocessing.py
Die Worte sind ganz anders (Bigramme?, Großbuchstaben, Ersetzung von Umlauten ä -> ae) als unser Ansatz, die Keras Methoden zu verwenden (einzelne Worde, alle lowercase):

167575: neuem_Gewand
167570: ionischen_Saeulen
167558: kuenstlich_angelegter

**Comment by oliver-pola** [comment]
Die Daten aus https://deepset.ai/german-word-embeddings sehen eher so aus, als wären sie mit dem Keras Prepocessing kompatibel. Vielleicht nehmen wir doch lieber die und müssen die dann wohl selbst einlesen und parsen.

**Comment by oliver-pola** [comment]
Habe nun doch auf die Daten aus https://deepset.ai/german-word-embeddings umgestellt. War etwas kompliziert, erst GloVe Vektoren laden, dann in Word2Vec-Text konvertieren und letztendlich noch mal in Word2Vec-Binary konvertieren, um etwas Platz zu sparen und die Ladezeiten zu verkürzen.

Nachdem man seine Posts in Wortlisten umgewandelt hat, reicht als Preprocessing für dieses Embedding dann ein einfaches word.lower()

Habe das auch gleich umgesetzt, siehe 15f84ff

Ist nun ziemlich RAM hungrig, musste bei mir deshalb auch die GPU abschalten (CUDA_VISIBLE_DEVICES = -1), auf der CPU rechnen lassen und zusätzlich noch aggressiv Speicher schleunigst wieder freigeben.

Sieht derzeit so aus:

python training.py SentimentNegative

```
Load Word2Vec embedding...
vocabulary size = 1309281
embedding dim = 300
Build embedding matrix...
embedding matrix shape = (1309282, 300)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding (Embedding)        (None, 80, 300)           392784600
_________________________________________________________________
spatial_dropout1d (SpatialDr (None, 80, 300)           0
_________________________________________________________________
lstm (LSTM)                  (None, 128)               219648
_________________________________________________________________
dense (Dense)                (None, 128)               16512
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 258
=================================================================
Total params: 393,021,018
Trainable params: 236,418
Non-trainable params: 392,784,600
_________________________________________________________________
None
Train on 3239 samples, validate on 360 samples
Epoch 1/50
3239/3239 - 119s - loss: 0.6985 - accuracy: 0.5178 - val_loss: 0.7002 - val_accuracy: 0.5028
Epoch 2/50
3239/3239 - 118s - loss: 0.6935 - accuracy: 0.5159 - val_loss: 0.7094 - val_accuracy: 0.4500
Epoch 3/50
3239/3239 - 118s - loss: 0.6893 - accuracy: 0.5211 - val_loss: 0.7020 - val_accuracy: 0.5361
...
Epoch 19/50
3239/3239 - 116s - loss: 0.6151 - accuracy: 0.6125 - val_loss: 0.7720 - val_accuracy: 0.5556
…
Epoch 43/50
3239/3239 - 116s - loss: 0.4494 - accuracy: 0.7780 - val_loss: 1.0047 - val_accuracy: 0.5556
…
Epoch 48/50
3239/3239 - 117s - loss: 0.4020 - accuracy: 0.8092 - val_loss: 1.0634 - val_accuracy: 0.5556
Epoch 49/50
3239/3239 - 117s - loss: 0.4048 - accuracy: 0.8036 - val_loss: 1.0266 - val_accuracy: 0.5444
Epoch 50/50
3239/3239 - 117s - loss: 0.3695 - accuracy: 0.8320 - val_loss: 1.0985 - val_accuracy: 0.5250
```

Sieht aber auch nicht wirklich besser aus als Random oder der vorherige Ansatz. Sicherlich muss man an den Parametern des LSTM und danach noch schrauben.
